<login>true</login>
<name>DMF本地版用户</name>
<pwd>05589497</pwd>
<isadmin>true</isadmin>
<permission><?=$AuthLevelString?></permission>
<level>弹幕抖M<?=$AuthLevelString?></level>
<shot>false</shot>
<chatid><?=$ChatId?></chatid>
<pid>0</pid>
<acceptguest>false</acceptguest>
<server>localhost</server>
<version>1299016295</version>